# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Download.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 340)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.save_location = QtWidgets.QTabWidget(self.centralwidget)
        self.save_location.setGeometry(QtCore.QRect(0, 0, 2000, 2000))
        self.save_location.setMaximumSize(QtCore.QSize(2000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.save_location.setFont(font)
        self.save_location.setStyleSheet("QTabWidget::pane {\n"
"        border-color: rgb(77,77,77);    \n"
"         background-color: rgb(0, 0, 0);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"}\n"
"QLineEdit { \n"
"    background-color: rgb(255, 255, 255);\n"
"   font: 9pt \"MS Shell Dlg 2\";\n"
"    border-style: none;\n"
"    border-bottom: 2px solid  rgb(0, 157, 235);\n"
"}\n"
"\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:#000000;    \n"
"}\n"
"QTabBar::tab{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color: rgb(0, 157, 235);\n"
"}\n"
"QTabWidget::panel {\n"
"    \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QMainWindow {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.save_location.setObjectName("save_location")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(90, 20, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.download = QtWidgets.QPushButton(self.tab_3)
        self.download.setGeometry(QtCore.QRect(390, 220, 111, 43))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.download.setFont(font)
        self.download.setStyleSheet("background-color: rgb(0, 157, 235);\n"
"border:2px solid rgb(0, 157, 235);\n"
"border-radius:5px;\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.download.setObjectName("download")
        self.saving_location = QtWidgets.QLineEdit(self.tab_3)
        self.saving_location.setGeometry(QtCore.QRect(150, 69, 511, 33))
        self.saving_location.setStyleSheet("")
        self.saving_location.setObjectName("saving_location")
        self.browse = QtWidgets.QPushButton(self.tab_3)
        self.browse.setGeometry(QtCore.QRect(660, 69, 90, 33))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.browse.setFont(font)
        self.browse.setStyleSheet("background-color: rgb(0, 157, 235);\n"
"border:2px solid rgb(0, 157, 235);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.browse.setObjectName("browse")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.url = QtWidgets.QLineEdit(self.tab_3)
        self.url.setGeometry(QtCore.QRect(150, 20, 601, 31))
        self.url.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.url.setObjectName("url")
        self.progressBar = QtWidgets.QProgressBar(self.tab_3)
        self.progressBar.setGeometry(QtCore.QRect(150, 180, 601, 23))
        self.progressBar.setStyleSheet("text-align: center;")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.save_location.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.browse_2 = QtWidgets.QPushButton(self.tab)
        self.browse_2.setGeometry(QtCore.QRect(660, 69, 90, 33))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.browse_2.setFont(font)
        self.browse_2.setStyleSheet("background-color: rgb(0, 157, 235);\n"
"border:2px solid rgb(0, 157, 235);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.browse_2.setObjectName("browse_2")
        self.saving_location_2 = QtWidgets.QLineEdit(self.tab)
        self.saving_location_2.setGeometry(QtCore.QRect(150, 69, 511, 33))
        self.saving_location_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.saving_location_2.setObjectName("saving_location_2")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(90, 20, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.progressBar_2 = QtWidgets.QProgressBar(self.tab)
        self.progressBar_2.setGeometry(QtCore.QRect(150, 180, 601, 23))
        self.progressBar_2.setStyleSheet("text-align: center;")
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.videoquality = QtWidgets.QComboBox(self.tab)
        self.videoquality.setGeometry(QtCore.QRect(150, 120, 361, 31))
        self.videoquality.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.videoquality.setObjectName("videoquality")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(60, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.youtube_url = QtWidgets.QLineEdit(self.tab)
        self.youtube_url.setGeometry(QtCore.QRect(150, 19, 511, 33))
        self.youtube_url.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.youtube_url.setObjectName("youtube_url")
        self.video_name = QtWidgets.QLabel(self.tab)
        self.video_name.setGeometry(QtCore.QRect(530, 120, 221, 31))
        self.video_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"border-style: none;\n"
"border-bottom: 2px solid  rgb(0, 157, 235);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.video_name.setObjectName("video_name")
        self.search_video = QtWidgets.QPushButton(self.tab)
        self.search_video.setGeometry(QtCore.QRect(660, 19, 91, 33))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.search_video.setFont(font)
        self.search_video.setStyleSheet("background-color: rgb(0, 157, 235);\n"
"border:2px solid rgb(0, 157, 235);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.search_video.setObjectName("search_video")
        self.download_2 = QtWidgets.QPushButton(self.tab)
        self.download_2.setGeometry(QtCore.QRect(390, 220, 111, 43))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.download_2.setFont(font)
        self.download_2.setStyleSheet("background-color: rgb(0, 157, 235);\n"
"border:2px solid rgb(0, 157, 235);\n"
"border-radius:5px;\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.download_2.setObjectName("download_2")
        self.save_location.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.browse_3 = QtWidgets.QPushButton(self.tab_2)
        self.browse_3.setGeometry(QtCore.QRect(660, 69, 90, 33))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.browse_3.setFont(font)
        self.browse_3.setStyleSheet("background-color: rgb(0, 157, 235);\n"
"border:2px solid rgb(0, 157, 235);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.browse_3.setObjectName("browse_3")
        self.saving_location_3 = QtWidgets.QLineEdit(self.tab_2)
        self.saving_location_3.setGeometry(QtCore.QRect(150, 69, 511, 33))
        self.saving_location_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.saving_location_3.setObjectName("saving_location_3")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(90, 20, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(10, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.progressBar_3 = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar_3.setGeometry(QtCore.QRect(150, 180, 601, 23))
        self.progressBar_3.setStyleSheet("text-align: center;")
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setObjectName("progressBar_3")
        self.PlaylistUrl = QtWidgets.QLineEdit(self.tab_2)
        self.PlaylistUrl.setGeometry(QtCore.QRect(150, 20, 601, 31))
        self.PlaylistUrl.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PlaylistUrl.setObjectName("PlaylistUrl")
        self.download_3 = QtWidgets.QPushButton(self.tab_2)
        self.download_3.setGeometry(QtCore.QRect(390, 220, 111, 43))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.download_3.setFont(font)
        self.download_3.setStyleSheet("background-color: rgb(0, 157, 235);\n"
"border:2px solid rgb(0, 157, 235);\n"
"border-radius:5px;\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.download_3.setObjectName("download_3")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(579, 120, 171, 31))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"border-style: none;\n"
"border-bottom: 2px solid  rgb(0, 157, 235);")
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(61, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.videoquality_2 = QtWidgets.QComboBox(self.tab_2)
        self.videoquality_2.setGeometry(QtCore.QRect(150, 120, 221, 31))
        self.videoquality_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: none;\n"
"border-bottom: 2px solid  rgb(0, 157, 235);")
        self.videoquality_2.setObjectName("videoquality_2")
        self.videoquality_2.addItem("")
        self.videoquality_2.addItem("")
        self.videoquality_2.addItem("")
        self.videoquality_2.addItem("")
        self.save_location.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.save_location.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "URL:"))
        self.download.setText(_translate("MainWindow", "Download"))
        self.browse.setText(_translate("MainWindow", "Browse"))
        self.label_2.setText(_translate("MainWindow", "Save Location:"))
        self.save_location.setTabText(self.save_location.indexOf(self.tab_3), _translate("MainWindow", "Any File"))
        self.browse_2.setText(_translate("MainWindow", "Browse"))
        self.label_4.setText(_translate("MainWindow", "URL:"))
        self.label_5.setText(_translate("MainWindow", "Save Location:"))
        self.label_6.setText(_translate("MainWindow", "Quality:"))
        self.video_name.setText(_translate("MainWindow", "Video Name"))
        self.search_video.setText(_translate("MainWindow", "Search"))
        self.download_2.setText(_translate("MainWindow", "Download"))
        self.save_location.setTabText(self.save_location.indexOf(self.tab), _translate("MainWindow", "Youtube video"))
        self.browse_3.setText(_translate("MainWindow", "Browse"))
        self.label_7.setText(_translate("MainWindow", "URL:"))
        self.label_8.setText(_translate("MainWindow", "Save Location:"))
        self.download_3.setText(_translate("MainWindow", "Download"))
        self.label_3.setText(_translate("MainWindow", "minutes remaining"))
        self.label_9.setText(_translate("MainWindow", "Quality:"))
        self.videoquality_2.setItemText(0, _translate("MainWindow", "1080"))
        self.videoquality_2.setItemText(1, _translate("MainWindow", "720"))
        self.videoquality_2.setItemText(2, _translate("MainWindow", "480"))
        self.videoquality_2.setItemText(3, _translate("MainWindow", "360"))
        self.save_location.setTabText(self.save_location.indexOf(self.tab_2), _translate("MainWindow", "Youtube playlist"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
